// <auto-generated />
namespace MyShop.DataAccess.SQL1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Inital21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inital21));
        
        string IMigrationMetadata.Id
        {
            get { return "202302231224070_Inital21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
